# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-22 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='detail',
            field=models.CharField(default='Nombre', max_length=255),
        ),
    ]
