# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-24 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0004_image_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnyFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(default='Nombre', max_length=255)),
                ('anyfile', models.FileField(upload_to='', verbose_name='anyfile')),
            ],
        ),
    ]
