# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-28 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0005_anyfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(default='Nombre', max_length=255)),
                ('detail2', models.CharField(default='Nombre', max_length=255)),
            ],
        ),
    ]
