# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-18 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0006_proof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proof',
            name='detail2',
        ),
        migrations.AddField(
            model_name='proof',
            name='anyfile',
            field=models.FileField(default=1, upload_to='', verbose_name='anyfile'),
            preserve_default=False,
        ),
    ]
