# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-06 21:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0011_userprofile_url_docs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filetype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nombre', max_length=255)),
                ('state', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('filesize', models.CharField(max_length=255)),
                ('url_docs', models.CharField(max_length=255)),
                ('last_mod', models.DateTimeField(auto_now_add=True)),
                ('state', models.IntegerField(default=1)),
                ('detail', models.CharField(max_length=255)),
                ('anyfile', models.FileField(upload_to='', verbose_name='anyfile')),
                ('filetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles_api.Filetype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Proof',
        ),
    ]
