# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-07 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0012_auto_20171206_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='anyfile',
            field=models.FileField(upload_to=models.CharField(max_length=255), verbose_name='anyfile'),
        ),
    ]
