# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-07 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import profiles_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0013_auto_20171207_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='anyfile',
            field=models.FileField(upload_to=profiles_api.models.magic_url, verbose_name='anyfile'),
        ),
    ]
