# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0014_auto_20171207_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='email',
            field=models.CharField(default='demo@test.cl', max_length=255),
            preserve_default=False,
        ),
    ]
