# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-16 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0019_auto_20171215_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='plan_id',
            field=models.IntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
