# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-16 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0020_userfile_plan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='plan_id',
            field=models.IntegerField(default=1),
        ),
    ]
