# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-16 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0021_auto_20171216_0424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfile',
            name='plan_id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='plan_id',
            field=models.IntegerField(default=1),
        ),
    ]
