# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-17 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0022_auto_20171216_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantype',
            name='storage',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
    ]
