# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-17 01:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0023_auto_20171217_0107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprocesshistory',
            old_name='remaining_storage',
            new_name='filled_storage',
        ),
        migrations.RenameField(
            model_name='userprocesshistory',
            old_name='remaining_storage_doc',
            new_name='filled_storage_doc',
        ),
        migrations.RenameField(
            model_name='userprocesshistory',
            old_name='remaining_storage_image',
            new_name='filled_storage_image',
        ),
        migrations.RenameField(
            model_name='userprocesshistory',
            old_name='remaining_storage_music',
            new_name='filled_storage_music',
        ),
        migrations.RenameField(
            model_name='userprocesshistory',
            old_name='remaining_storage_video',
            new_name='filled_storage_video',
        ),
    ]
