# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0024_auto_20171217_0129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('given_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserCollector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collector_rut', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='codes',
            name='collector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles_api.UserCollector'),
        ),
    ]
