# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-11 02:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0026_userprofile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.IntegerField(default=1)),
                ('init_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now_add=True)),
                ('current', models.IntegerField(default=1)),
                ('total', models.IntegerField(default=1)),
                ('status', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityid', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('init_date', models.CharField(max_length=500)),
                ('end_date', models.CharField(max_length=500)),
                ('total_files', models.CharField(max_length=500)),
                ('current_files', models.CharField(max_length=500)),
                ('detail', models.CharField(max_length=500)),
                ('bytes', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('init_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=255)),
                ('filesize', models.CharField(max_length=255)),
                ('detail', models.CharField(max_length=500)),
                ('filechunk', models.CharField(max_length=500)),
                ('complete', models.IntegerField(default=1)),
                ('status', models.IntegerField(default=1)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles_api.Action')),
                ('filetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles_api.Filetype')),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileid', models.CharField(max_length=500)),
                ('activityid', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('filename', models.CharField(max_length=500)),
                ('filesize', models.CharField(max_length=500)),
                ('filetype', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=500)),
                ('detail', models.CharField(max_length=500)),
                ('bytes', models.CharField(max_length=500)),
                ('path', models.CharField(max_length=500)),
            ],
        ),
    ]
